config/routes.rb
Rails.application.routes.draw do
  resources :paragraphs
  resources :documents

  root 'documents#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  has_many :paragraphs
end

app/models/paragraph.rb
class Paragraph < ApplicationRecord
  belongs_to :document
  validates :document_id, :body, presence: true

  audited only: :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @paragraphs = @document.paragraphs
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title)
    end
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  before_action :set_paragraph, only: [:show, :edit, :update, :destroy]

  # GET /paragraphs
  # GET /paragraphs.json
  def index
    @paragraphs = Paragraph.all
  end

  # GET /paragraphs/1
  # GET /paragraphs/1.json
  def show
  end

  # GET /paragraphs/new
  def new
    @paragraph = Paragraph.new
  end

  # GET /paragraphs/1/edit
  def edit
  end

  # POST /paragraphs
  # POST /paragraphs.json
  def create
    @paragraph = Paragraph.new(paragraph_params)

    respond_to do |format|
      if @paragraph.save
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully created.' }
        format.json { render :show, status: :created, location: @paragraph }
      else
        format.html { render :new }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paragraphs/1
  # PATCH/PUT /paragraphs/1.json
  def update
    respond_to do |format|
      if @paragraph.update(paragraph_params)
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully updated.' }
        format.json { render :show, status: :ok, location: @paragraph }
      else
        format.html { render :edit }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paragraphs/1
  # DELETE /paragraphs/1.json
  def destroy
    @paragraph.destroy
    respond_to do |format|
      format.html { redirect_to paragraphs_url, notice: 'Paragraph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paragraph
      @paragraph = Paragraph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paragraph_params
      params.require(:paragraph).permit(:document_id, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/views/documents/_form.html.erb
<%= form_for(document) do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document Title</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', documents_path %>
<br><br><br>

<h1><%= @document.title %></h1>

<%= link_to 'Edit', edit_document_path(@document) %>
<br><br><br>

<%= render 'paragraphs/index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuideControlSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paragraphs/_form.html.erb
<%= form_for(paragraph) do |f| %>
  <% if paragraph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paragraph.errors.count, "error") %> prohibited this paragraph from being saved:</h2>

      <ul>
      <% paragraph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :document_id %>
    <%=  select("paragraph", "document_id", Document.all.collect {|d| [d.title, d.id] }, { include_blank: false }) %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paragraphs/_index.html.erb
<div>
  <% @paragraphs.each do |paragraph| %>
    <p><%= paragraph.body %></p>
    <%= link_to 'Edit paragraph', edit_paragraph_path(paragraph) %>
    <%= link_to 'Delete', paragraph, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br><br><br>
  <% end %>
</div>

<br>

<%= link_to 'Add new paragraph', new_paragraph_path %>

app/views/paragraphs/edit.html.erb
<h1>Editing Paragraph</h1>

<%= render 'form', paragraph: @paragraph %>

<%= link_to 'Show', @paragraph %> |
<%= link_to 'Back', :back %>

app/views/paragraphs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paragraphs</h1>

<table>
  <thead>
    <tr>
      <th>Document</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paragraphs.each do |paragraph| %>
      <tr>
        <td><%= paragraph.document_id %></td>
        <td><%= paragraph.body %></td>
        <td><%= link_to 'Show', paragraph %></td>
        <td><%= link_to 'Edit', edit_paragraph_path(paragraph) %></td>
        <td><%= link_to 'Delete', paragraph, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paragraph', new_paragraph_path %>

app/views/paragraphs/new.html.erb
<h1>New Paragraph</h1>

<%= render 'form', paragraph: @paragraph %>

<%= link_to 'Back', paragraphs_path %>

app/views/paragraphs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document:</strong>
  <%= @paragraph.document.title %>
</p>

<p>
  <strong>Current body:</strong>
  <%= @paragraph.body %>
</p>

<p>
  <strong>Previous Version:</strong>
  <%= @paragraph.revision(:previous).body %>
</p>

<p><strong>What's the difference:</strong></p>
<table>
  <tbody>
    <td><%= Diffy::SplitDiff.new(@paragraph.revision(:previous).body, @paragraph.body, :format => :html).left.html_safe%></td>
    <td><%= Diffy::SplitDiff.new(@paragraph.revision(:previous).body, @paragraph.body, :format => :html).right.html_safe%></td>
  </tbody>
</table>

<!-- <p>
  <strong>What's the difference:</strong>
  <%= Diffy::Diff.new(@paragraph.revision(:previous).body, @paragraph.body).to_s(:html).html_safe%>
</p> -->

<br><hr><br>

<div class="revision">
  <ol>
    <% @paragraph.revisions.each do |revision| %>
      <li><%= revision.body %></li>
    <% end %>
  </ol>
</div>

<br><hr><br>

<%= link_to 'Edit', edit_paragraph_path(@paragraph) %> |
<%= link_to 'Back', paragraphs_path %>